### ISSUE TITLE
AssertionError from gslrandom

### ISSUE THREAD

**Issue by mihirfk** [slinderman/pyhawkes#7] opened 2017-02-21 10:23 UTC
Hello
I just installed pyhawkes.
When trying to run the discrete_model demo I  run into the following error.
Any idea what is going wrong/ how to fix this?

>>> for itr in xrange(N_samples):
...     test_model.resample_model()
...     lps.append(test_model.log_probability())
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/mihirkale.s/lib/python/pyhawkes/pyhawkes/models.py", line 1207, in resample_model
    p.resample()
  File "/home/mihirkale.s/lib/python/pyhawkes/pyhawkes/internals/parents.py", line 262, in resample
    self._resample_Z_gsl()
  File "/home/mihirkale.s/lib/python/pyhawkes/pyhawkes/internals/parents.py", line 255, in _resample_Z_gsl
    multinomial(self.pyrngs, Sk, P, out=Zk)
  File "gslrandom/gslrandom.pyx", line 114, in gslrandom.gslrandom.multinomial (gslrandom/gslrandom.cpp:3699)
    assert isinstance(rng, PyRNG)
AssertionError

**Comment by jc17** [comment] 2017-03-27 16:57
Hi,

Any updates on this..?? I am facing the similar issue..

**Comment by slinderman** [comment] 2017-03-27 17:57
This looks like a version issue with `gslrandom`.  I just uploaded the latest version to pypi. Can you please try upgrading `gslrandom` with:

```
pip install --upgrade gslrandom
``` 

I've also updated `pyhawkes` to support python3 with https://github.com/slinderman/pyhawkes/commit/843b5ed09ab4e32918a89c8ce43ccc7153a4109f.  
Please pull the latest version of pyhawkes as well and let me know if this issue persists.

Thanks!

**Comment by jc17** [comment] 2017-03-27 18:16
Hi Scott,

Tried upgrading gslrandom, but there some issue with cython compilation. Here is snapshot:



> Collecting gslrandom
>   Using cached gslrandom-0.1.3.tar.gz
>     Complete output from command python setup.py egg_info:
>     
>     Error compiling Cython file:
>     ------------------------------------------------------------
>     ...
>     ###########################
> Collecting gslrandom
>   Using cached gslrandom-0.1.3.tar.gz
>     Complete output from command python setup.py egg_info:
>     
>     Error compiling Cython file:
>     ------------------------------------------------------------
>     ...
>     ###############################################################################
>     #                                 Multinomial                                 #
>     ###############################################################################
>     
>     cdef extern from "cgslrandom.h":
>         double sample_multinomial(BasicRNG* brng,
>                                  ^
>     ------------------------------------------------------------
>     
>     gslrandom/gslrandom.pyx:44:30: 'BasicRNG' is not a type identifier
>     
>     Error compiling Cython file:
>     ------------------------------------------------------------
>     ...
>     ###############################################################################
>     #                                 Dirichlet                                   #
>     ###############################################################################
>     
>     cdef extern from "cgslrandom.h":
>         void sample_dirichlet (BasicRNG* brng,
>                               ^
>     ------------------------------------------------------------
>     
>     gslrandom/gslrandom.pyx:325:27: 'BasicRNG' is not a type identifier
>     
>     Error compiling Cython file:
>     ------------------------------------------------------------
>     ...
>         cdef size_t K = p_IK.shape[1]
>         assert p_IK.shape[0] == I
>         assert n_IK.shape[0] == I
>         assert n_IK.shape[1] == K
>     
>         cdef vector[BasicRNG*] rngsv
>                             ^
>     ------------------------------------------------------------
>     
>     gslrandom/gslrandom.pyx:101:25: 'BasicRNG' is not a type identifier
>     
>     Error compiling Cython file:
>     ------------------------------------------------------------
>     ...
>         cdef size_t I = alpha_IK.shape[0]
>         cdef size_t K = alpha_IK.shape[1]
>         assert theta_IK.shape[0] == I
>         assert theta_IK.shape[1] == K
>     
>         cdef vector[BasicRNG*] rngsv
>                             ^
>     ------------------------------------------------------------
>     
>     gslrandom/gslrandom.pyx:367:25: 'BasicRNG' is not a type identifier
>     
>     Error compiling Cython file:
>     ------------------------------------------------------------
>     ...
>     
>     # Expose the RNG class to Python
>     cdef class PyRNG:
>     
>         def __cinit__(self, unsigned long seed=0):
>             self.thisptr = new BasicRNG(seed)
>                               ^
>     ------------------------------------------------------------
>     
>     gslrandom/gslrandom.pyx:34:27: 'BasicRNG' is not a type identifier
>     
>     Error compiling Cython file:
>     ------------------------------------------------------------
>     ...
>     
>     # Expose the RNG class to Python
>     cdef class PyRNG:
>     
>         def __cinit__(self, unsigned long seed=0):
>             self.thisptr = new BasicRNG(seed)
>                               ^
>     ------------------------------------------------------------
>     
>     gslrandom/gslrandom.pyx:34:27: new operator can only be applied to a C++ class
>     Compiling gslrandom/gslrandom.pyx because it depends on /usr/local/lib/python2.7/dist-packages/Cython/Includes/openmp.pxd.
>     [1/1] Cythonizing gslrandom/gslrandom.pyx
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-2Lafdf/gslrandom/setup.py", line 19, in <module>
>         ext_modules=cythonize('**/*.pyx'),
>       File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 934, in cythonize
>         cythonize_one(*args)
>       File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 1056, in cythonize_one
>         raise CompileError(None, pyx_file)
>     Cython.Compiler.Errors.CompileError: gslrandom/gslrandom.pyx
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-2Lafdf/gslrandom/
> 

Did also try installing gslrandom with pip3.6, that too shows some error related to cython compilation.

Thanks

**Comment by slinderman** [comment] 2017-03-27 20:45
Yikes, I forgot to include the `gslrandom.pxd` file in the Manifest, but my tests didn't catch it because pip was caching files.  I've updated gslrandom and confirmed that 

```pip install --no-cache-dir gslrandom```

works for me. 

Can you try this once more? 

Thanks again.

**Comment by jc17** [comment] 2017-03-27 20:58
Hey, Its seems good now. Tried running "discrete_demo.py", worked well. 

Thanks a lot. 👍

**Comment by slinderman** [comment] 2017-03-27 23:46
Great, I also made `gslrandom` optional in the most recent commits.  You'll still want it for high-performance parent updates, but at least it will still install out of the box for basic users.  See https://github.com/slinderman/pyhawkes/commit/e592afa752693bbad48a79cbdec1922289f528d9 I'm going to go ahead and close this issue now.

**Closed by slinderman** 2017-03-27 23:46 UTC
